---
name: Development push workflow

on:
  push:
    branches:
      - development

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: write  

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  IMAGE_REPOSITORY: dev
  IMAGE_REGISTRY: gigatech
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  setup:
    name: Setup
    permissions: read-all
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-setup.yaml@main

  lint:
    name: Lint Code Base
    needs: [setup]
    permissions:
      contents: read
      statuses: write
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-super-linter.yaml@main
    with:
      ### For a DevOps-focused repository. Prevents some code-language linters from running
      ### temporarily set this to bypass ts lint
      devops-only: false
      ### A regex to exclude files from linting
      ### defaults to empty
      filter-regex-exclude: ".*[src|(github)]\\/.*"

  secret-scan:
    name: Secret Scan
    needs: [setup]
    permissions: read-all
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-secret-scan.yaml@main

  spellcheck:
    name: Spellcheck codebase
    needs: [setup]
    permissions:
      contents: write
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-spellcheck.yaml@main

  dependency-check:
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-dependency-check.yaml@main
    needs: [setup]
    permissions: read-all
    with:
      retentionDays: 3

  report-code-quality-metric:
    name: Report Code Quality Metric
    needs: [lint, secret-scan, spellcheck]
    if: always()
    permissions: read-all
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-metric-quality-gate.yaml@main
    secrets: inherit
    with:
        lintStatus: ${{ needs.lint.result }}
        secretScanStatus: ${{ needs.secret-scan.result }}
        spellcheckStatus: ${{ needs.spellcheck.result }}
        sourceId: "ari:cloud:compass:c5f85481-25ba-4ff0-afac-a4bc0082db80:metric-source/0938370a-36b8-4157-8b2d-4cd87e26cf36/4ac547b0-1da9-4889-a3c5-64911f46f3f6"

  build:
    name: Build
    needs: [setup, spellcheck, lint]
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: github.actor != 'dependabot[bot]'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}  # The base image name

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.actor != 'dependabot[bot]' }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
