---
name: Development push workflow

on:
  push:
    branches:
      - development

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: write  

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  IMAGE_REPOSITORY: cds
  ECS_SERVICE_NAME: cds-dev-ecs-svc-name
  ECS_CLUSTER_NAME: prometheus-cluster-prod

jobs:
  setup:
    name: Setup
    permissions: read-all
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-setup.yaml@main

  lint:
    name: Lint Code Base
    needs: [setup]
    permissions:
      contents: read
      statuses: write
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-super-linter.yaml@main
    with:
      ### For a DevOps-focused repository. Prevents some code-language linters from running
      ### temporarily set this to bypass ts lint
      devops-only: false
      ### A regex to exclude files from linting
      ### defaults to empty
      filter-regex-exclude: "[src|.github]/**"

  secret-scan:
    name: Secret Scan
    needs: [setup]
    permissions: read-all
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-secret-scan.yaml@main

  spellcheck:
    name: Spellcheck codebase
    needs: [setup]
    permissions:
      contents: write
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-spellcheck.yaml@main

  dependency-check:
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-dependency-check.yaml@main
    needs: [setup]
    permissions: read-all
    with:
      retentionDays: 3

  report-code-quality-metric:
    name: Report Code Quality Metric
    needs: [lint, secret-scan, spellcheck]
    if: always()
    permissions: read-all
    uses: GigaTech-net/public-reusable-workflows/.github/workflows/rw-metric-quality-gate.yaml@main
    secrets: inherit
    with:
        lintStatus: ${{ needs.lint.result }}
        secretScanStatus: ${{ needs.secret-scan.result }}
        spellcheckStatus: ${{ needs.spellcheck.result }}
        sourceId: "ari:cloud:compass:c5f85481-25ba-4ff0-afac-a4bc0082db80:metric-source/0938370a-36b8-4157-8b2d-4cd87e26cf36/4ac547b0-1da9-4889-a3c5-64911f46f3f6"

  build:
    name: Build
    needs: [setup, spellcheck, lint]
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: build docker image
        id: build-image
        env:
          ECR_REPOSITORY: cds
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # shellcheck disable=SC2086
          {
            GA=${{ github.actor }}

            if [ "$GA" == "dependabot[bot]" ]; then
              ECR_REGISTRY="BOT-ACCOUNT.dkr.ecr.BOT-REGION.amazonaws.com"
            else
              ECR_REGISTRY="gigatech"
            fi 
            docker build -t "$ECR_REGISTRY/${{ env.IMAGE_REPOSITORY }}":"$IMAGE_TAG" .
            {
              echo "image=$ECR_REGISTRY/${{ env.IMAGE_REPOSITORY }}:$IMAGE_TAG";
              echo "IMAGE_TAG=$IMAGE_TAG";
              echo "ECR_REGISTRY=$ECR_REGISTRY";
            } >> $GITHUB_OUTPUT
          }
