name: main branch build and push to dockerhub

on:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  call-trufflehog-scan:
    uses: GigaTech-net/reusable-workflows/.github/workflows/rw-trufflehog-scan.yaml@main

  build_push_to_dockerhub:
    runs-on: ubuntu-latest
    name: Docker build, tag, push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, Tag, Push
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: gigatech/dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
